### ISSUE TITLE
Access Permission issue when downloading features

### ISSUE THREAD

**Issue by agupt013** [fpv-iplab/rulstm#10]
Hi,
I'm trying to download the lmdb file for features using ./scripts/download_data.sh and ./scripts/download_data_full.sh.
However, I'm getting an 403 error saying I don't have permission to access the resources.
Can you please share the accessible links?

Thanks,
Akash

**Comment by antoninofurnari** [comment]
Hi Akash,

The link should work again now. Thank you for pointing out the issue.

Best,
Antonino

**Comment by agupt013** [comment]
It is workin now. Thank you for the quick response!

**Comment by Yu-Wu** [comment]
Hi Antonino, 

It seems the link breaks again.
e.g., https://iplab.dmi.unict.it/sharing/rulstm/features/flow_full/data.mdb

Could you please check this url?

Thanks,
Yu

**Comment by antoninofurnari** [comment]
The link is now up again as explained here https://github.com/fpv-iplab/rulstm/issues/11#issuecomment-668206155

Thanks for your patience.

Best,
Antonino
