### ISSUE TITLE
FastRCNN detector

### ISSUE THREAD

**Issue by vmurahari3** [fpv-iplab/rulstm#14]
I was wondering if you had object recall metrics of the released FastRCNN weights? I looked at some of the detections and they didn't seem to great. Might be a bug on my end too.

**Comment by antoninofurnari** [comment]
Hello, unfortunately we did not compute object recall at the time. Considering that you closed the issue, is the problem solved?

**Comment by vmurahari3** [comment]
Thanks for replying! I forgot to add the "background" class while visualizing the boxes and object ids were off by one as a result. The object detections look great now!
