### ISSUE TITLE
download data ek55 error

### ISSUE THREAD

**Issue by r3ward** [fpv-iplab/rulstm#19]
When running the following script to get data:  ./scripts/download_data_ek55.sh

The download does not initiate, with the following error displayed:
'0curl: (7) Failed to connect to iplab.dmi.unict.it port 443: No route to host'

**Comment by antoninofurnari** [comment]
Hello, thanks for notifying me. There has been a issue at our servers which our technicians will likely solve tomorrow.

Just try tomorrow, it should work.

Antonino

**Comment by antoninofurnari** [comment]
Just checked it's working now.

Antonino

**Comment by ApoorvaBeedu** [comment]
Hello, I believe the download issue is back.
