### ISSUE TITLE
[Meccano] Testing

### ISSUE THREAD

**Issue by Victoria-Manousaki** [fpv-iplab/rulstm#23]
Hello,

In the main.py file provided for the Meccano dataset:

1. In line 679 (https://github.com/fpv-iplab/MECCANO/blob/169b023dc0b61989a8fc69dcf8c613748c88a64d/RULSTM_files/main.py#L679)
the function get_meccano_scores is required to return 4 values but the function returns 3 by default.

2. Lines 685-686 raise an error because the verb_scores and noun_scores are not calculated for Meccano.

Any recommendations/fixes?

Thank you for your time,
Victoria

**Comment by antoninofurnari** [comment]
Dear Victoria,

Maybe @francescoragusa, who is the maintainer of the MECCANO repository can help answer this issue better than me.

Best,
Antonino

**Comment by Victoria-Manousaki** [comment]
Thank you for the quick response!
I will open an issue there!

--
Victoria
