### ISSUE TITLE
Hello, I would like to ask, I want to use your model for the assembly line operation data set on the worker's workshop to predict the next action of the worker. Do you think this idea is okay? And how should I label my dataset?

### ISSUE THREAD

**Issue by 1848739617** [fpv-iplab/rulstm#25]
![1669364339318](https://user-images.githubusercontent.com/56751342/203934188-ba6ff151-c607-4e0a-833a-032e4fca918b.jpg)

**Comment by 1848739617** [comment]
Hello, how should I input my data set into your model?

**Comment by antoninofurnari** [comment]
Please refer to this issue: https://github.com/fpv-iplab/rulstm/issues/24
