### ISSUE TITLE
Features download error

### ISSUE THREAD

**Issue by ApoorvaBeedu** [fpv-iplab/rulstm#31]
Hello, 

When running the ./scripts/download_data_ek55.sh script to get data, the following error occurs.
curl: (7) Failed to connect to iplab.dmi.unict.it port 443 : No route to host'

**Comment by antoninofurnari** [comment]
Hello, thanks for notifying this. We have issues with our server. This will likely be fixed on Monday.

**Comment by ApoorvaBeedu** [comment]
Thank you! 
It does look fixed today.
