### ISSUE TITLE
Docker image for detectron

### ISSUE THREAD

**Issue by Gregz9** [fpv-iplab/rulstm#35]
Hi, 

I am not able to setup a docker image to run the FasterRCNN for feature extraction with my own custom data. Is there any chance that you have any Dockerfile  or docker image which I could use? Or any version of the code which has been transitioned to detectron2?

**Comment by antoninofurnari** [comment]
Hi, thank you for your message. No, unfortunately, there is no docker file and we have not transitioned to docker2.
