### ISSUE TITLE
FPS for RGB, Flow and Object Features

### ISSUE THREAD

**Issue by guanglun95** [fpv-iplab/rulstm#6]
Thank you very much for your excellent work. I wonder whether the rgb, flow and object features come from the same frames sampled at the fps of 4 (as you mentioned in readme)?

**Comment by antoninofurnari** [comment]
We are providing two sets of pre-extracted features, which can be downloaded with two scripts:
- download_data.sh: downloads the "small" set, which includes features for frames subsampled at 4fps;
- download_data_full.sh: downloads the "large" set, which includes features for all videos at 30fps (the videos have been previously re-encoded at 30fps)
